## JPL DE441 Ephemeris

```{r include = FALSE}
source("_common.R")
```

The JPL Development Ephemeris 441 (DE441) provides accurate data on the positions of the planets, moon, sun, nutation angles, and lunar librations. The time frame for DE441 is:

- Start Epoch: Julian Day Number = -3100015.5
- Start Epoch: Julian Calendar Date = August 15, -13200
- Final Epoch: Julian Day Number = 8000016.5
- Final Epoch: Gregorian Calendar Date = March 15, 17191

## DE441 Files and File Structure

+-------------------------------+-----------+-----------------+------------------------------------+--------------+--------------+
| Name                          | Reference | Units           | Coordinates                        | Coefficients | Subintervals |
+:==============================+===========+=================+====================================+==============+==============+
| Mercury                       | SSB       | km              | x, y, z                            | 14           | 4            |
+-------------------------------+-----------+-----------------+------------------------------------+--------------+--------------+
| Venus                         | SSB       | km              | x, y, z                            | 10           | 2            |
+-------------------------------+-----------+-----------------+------------------------------------+--------------+--------------+
| EMB                           | SSB       | km              | x, y, z                            | 13           | 2            |
+-------------------------------+-----------+-----------------+------------------------------------+--------------+--------------+
| Mars                          | SSB       | km              | x, y, z                            | 11           | 1            |
+-------------------------------+-----------+-----------------+------------------------------------+--------------+--------------+
| Jupiter                       | SSB       | km              | x, y, z                            | 8            | 1            |
+-------------------------------+-----------+-----------------+------------------------------------+--------------+--------------+
| Saturn                        | SSB       | km              | x, y, z                            | 7            | 1            |
+-------------------------------+-----------+-----------------+------------------------------------+--------------+--------------+
| Uranus                        | SSB       | km              | x, y, z                            | 6            | 1            |
+-------------------------------+-----------+-----------------+------------------------------------+--------------+--------------+
| Neptune                       | SSB       | km              | x, y, z                            | 6            | 1            |
+-------------------------------+-----------+-----------------+------------------------------------+--------------+--------------+
| Pluto                         | SSB       | km              | x, y, z                            | 6            | 1            |
+-------------------------------+-----------+-----------------+------------------------------------+--------------+--------------+
| Moon                          | Earth     | km              | x, y, z                            | 13           | 8            |
+-------------------------------+-----------+-----------------+------------------------------------+--------------+--------------+
| Sun                           | SSB       | km              | x, y, z                            | 11           | 2            |
+-------------------------------+-----------+-----------------+------------------------------------+--------------+--------------+
| Nutations                     |           | radians         | $\Delta$$\psi$, $\Delta$$\epsilon$ | 0            | 0            |
+-------------------------------+-----------+-----------------+------------------------------------+--------------+--------------+
| Lunar Mantle Librations       |           | radians         | $\phi$, $\theta$, $\psi$           | 10           | 4            |
+-------------------------------+-----------+-----------------+------------------------------------+--------------+--------------+
| Lunar Mantle Angular Velocity |           | radians per day | $\omega_x$, $\omega_y$, $\omega_z$ | 0            | 0            |
+-------------------------------+-----------+-----------------+------------------------------------+--------------+--------------+
| TT-TDB                        |           | seconds         |                                    | 0            | 0            |
+-------------------------------+-----------+-----------------+------------------------------------+--------------+--------------+

: DE440-441 Bodies {#tbl-de440-441bodies .striped .hover}

See @tbl-de440-441bodies
