
library(logger)
library(arrow)
library(writexl)
library(readxl)
library(dplyr)
library(stringr)
library(httr)
library(jsonlite)
library(duckdb)

source(here("src", "R", "constants.R"))
source(here("src", "R", "ProcessRawDE441Data", "ProcessDE441FileList.R"))
source(here("src", "R", "ProcessRawDE441Data", "ProcessDE441RawData.R"))
source(here("src", "R", "ProcessRawDE441Data", "ProcessDE441Mercury.R"))
source(here("src", "R", "ProcessRawDE441Data", "ProcessDE441Venus.R"))
source(here("src", "R", "ProcessRawDE441Data", "ProcessDE441EMB.R"))
source(here("src", "R", "ProcessRawDE441Data", "ProcessDE441Mars.R"))
source(here("src", "R", "ProcessRawDE441Data", "ProcessDE441Jupiter.R"))
source(here("src", "R", "ProcessRawDE441Data", "ProcessDE441Saturn.R"))
source(here("src", "R", "ProcessRawDE441Data", "ProcessDE441Uranus.R"))
source(here("src", "R", "ProcessRawDE441Data", "ProcessDE441Neptune.R"))
source(here("src", "R", "ProcessRawDE441Data", "ProcessDE441Pluto.R"))
source(here("src", "R", "ProcessRawDE441Data", "ProcessDE441Sun.R"))
source(here("src", "R", "ProcessRawDE441Data", "ProcessDE441Moon.R"))
source(here("src", "R", "ProcessRawDE441Data", "ProcessDE441Nutation.R"))
source(here("src", "R", "ProcessDE441ParquetData", "BuildMasterDE441Data.R"))
source(here("src", "R", "ProcessDE441ParquetData", "BuildMasterDE441Mercury.R"))
source(here("src", "R", "ProcessDE441ParquetData", "BuildMasterDE441Venus.R"))
source(here("src", "R", "ProcessDE441ParquetData", "BuildMasterDE441EMB.R"))
source(here("src", "R", "ProcessDE441ParquetData", "BuildMasterDE441Mars.R"))
source(here("src", "R", "ProcessDE441ParquetData", "BuildMasterDE441Jupiter.R"))
source(here("src", "R", "ProcessDE441ParquetData", "BuildMasterDE441Saturn.R"))
source(here("src", "R", "ProcessDE441ParquetData", "BuildMasterDE441Uranus.R"))
source(here("src", "R", "ProcessDE441ParquetData", "BuildMasterDE441Neptune.R"))
source(here("src", "R", "ProcessDE441ParquetData", "BuildMasterDE441Pluto.R"))
source(here("src", "R", "ProcessDE441ParquetData", "BuildMasterDE441Moon.R"))
source(here("src", "R", "ProcessDE441ParquetData", "BuildMasterDE441Sun.R"))
source(here("src", "R", "ProcessDE441ParquetData", "BuildMasterDE441Nutation.R"))
source(here("src", "R", "CreateJulianDayNumberTable.R"))
source(here("src", "R", "Date.R"))
source(here("src", "R", "UnitConversions.R"))
source(here("src", "R", "CreateDatabase", "CreateDE441DE440Database.R"))
source(here("src", "R", "DE441SolarSystemPosVel", "PositionMercurySSB.R"))
source(here("src", "R", "DE441SolarSystemPosVel", "PositionVenusSSB.R"))
source(here("src", "R", "ProcessRawDE440Data", "ProcessDE440RawData.R"))
source(here("src", "R", "ProcessRawDE440Data", "ProcessDE440Mercury.R"))
source(here("src", "R", "ProcessRawDE440Data", "ProcessDE440Venus.R"))
source(here("src", "R", "ProcessRawDE440Data", "ProcessDE440EMB.R"))
source(here("src", "R", "ProcessRawDE440Data", "ProcessDE440Mars.R"))
source(here("src", "R", "ProcessRawDE440Data", "ProcessDE440Jupiter.R"))
source(here("src", "R", "ProcessRawDE440Data", "ProcessDE440Saturn.R"))
source(here("src", "R", "ProcessRawDE440Data", "ProcessDE440Uranus.R"))
source(here("src", "R", "ProcessRawDE440Data", "ProcessDE440Neptune.R"))
source(here("src", "R", "ProcessRawDE440Data", "ProcessDE440Pluto.R"))
source(here("src", "R", "ProcessRawDE440Data", "ProcessDE440Sun.R"))
source(here("src", "R", "ProcessRawDE440Data", "ProcessDE440Moon.R"))
source(here("src", "R", "ProcessRawDE440Data", "ProcessDE440Nutation.R"))



